name: Push
on:
  push
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  build:
    name: Build ares (primary)
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      codesign: false
      official: false
  build-aux:
    name: Build ares (auxiliary)
    uses: ./.github/workflows/build-aux.yml
    secrets: inherit
  release:
    name: Release
    needs: build
    secrets: inherit
    uses: ./.github/workflows/release.yml
    with:
      notarize: false